---
abstract: 'turn your Moose class into a singleton'
author:
  - 'Shawn M Moore <sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: Perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Singleton
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.82
resources:
  license: http://dev.perl.org/licenses/
version: 0.21
